import "react-toastify/dist/ReactToastify.css";
import { Footer } from "@/components/principal/Footer";
import { Header } from "@/components/principal/Header";
import { ToastContainer } from 'react-toastify';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Drago Tech",
  description: "Generated by create next app",
};

export default function PrincipalLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <>
        <Header />
        {children}
        <ToastContainer position="top-right" theme="light" />
        <Footer />
    </>
  );
}
