import { SideBar } from "@/components/admin/sideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Drago Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <>
        <div className="flex">
            <SideBar />
            <div className="flex-1">
              {children}
            </div>
        </div>
    </>
  );
}
