import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Drago Blog",
  description: "Generated by create next app",
};

export default function PrimeLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <>
        {children}
    </>
  );
}
