import type { Metadata } from "next";
import "./global.css";
import { Header } from "@/components/blog/Header";
import { Footer } from "@/components/blog/Footer";

export const metadata: Metadata = {
  title: "Drago Blog",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <>
        <Header />
        {children}
        <Footer />
    </>
  );
}
